<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TelDemo.WebApi\ActivityExtensions.cs" Link="ActivityExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Amazon.Runtime" />
    <Using Include="Amazon.SQS" />
    <Using Include="Amazon.SQS.Model" />
    <Using Include="OpenTelemetry" />
    <Using Include="OpenTelemetry.Context.Propagation" />
    <Using Include="OpenTelemetry.Logs" />
    <Using Include="OpenTelemetry.Metrics" />
    <Using Include="OpenTelemetry.Resources" />
	<Using Include="OpenTelemetry.Trace" />
	<Using Include="System.Diagnostics" />
    <Using Include="System.Text" />
    <Using Include="RabbitMQ.Client" />
    <Using Include="RabbitMQ.Client.Events" />
    <Using Include="TelDemo.Backend.Services" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.14" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AWS" Version="1.19.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireServiceDefaults\AspireServiceDefaults.csproj" />
  </ItemGroup>

</Project>
