<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TelDemo.WebApi\ActivityExtensions.cs" Link="ActivityExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="OpenTelemetry" />
    <Using Include="OpenTelemetry.Trace" />
    <Using Include="System.Diagnostics" />
    <Using Include="TelDemo.Frontend.Models" />
    <Using Include="TelDemo.Frontend.Services" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireServiceDefaults\AspireServiceDefaults.csproj" />
  </ItemGroup>

</Project>
